---
- hosts: nginx
  remote_user: root
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Remove file
      file:
        path: /etc/nginx/nginx.conf
        state: absent
    - name: Download Conf
      get_url:
        url: https://raw.githubusercontent.com/runningoec/nginx/master/nginx-conf/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: '644'
    - name: open https
      firewalld:
      service: https
        permanent: yes
        state: enabled
    - name: open http
      firewalld:
      service: http
        permanent: yes
        state: enabled
    - name: Allow http to listen on tcp port 8991
      seport:
        ports: 9091
        proto: tcp
        setype: http_port_t
        state: present
    - name: Create a directory if it does not exist
      file:
        path: /var/cache/nginx/wowza_cache_temp
        state: directory
        mode: '0755'
    - name: Bounce Nginx
      service:
        name: nginx
        state: restarted
