---
- hosts: nginx
  remote_user: root
  tasks:
    - name: Install Nginx
      yum:
        name: Nginx
        state: present
    - name: Remove file
      file:
        path: /etc/nginx/nginx.conf
        state: absent
    - name: Download Conf
      get_url:
        url: https://raw.githubusercontent.com/runningoec/nginx/master/nginx-conf/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: '644'
    - name: Bounce Nginx
      service:
        name: nginx
        state: restarted
